---
output: html_document
---
```{r}
library('varhandle')
library('flexsurv')
```

```{r,warning=FALSE}
new_rls<-read.csv("rls 2016-08-02.csv")


my.data=new_rls

#my.data<-my.data[complete.cases(my.data$ref_lifespan_mean),]

big_data<-my.data[!duplicated(my.data$ref_lifespans),] 

#you uniquely determine the ref_lifespans of each experiments individually


# ref_lifespan_mean is at [,26]

big_data= big_data[!is.na(big_data[,26]), ]

#big_data = big_data[complete.cases(big_data$ref_lifespan_mean),]
for (k in 1:length(sort(big_data$ref_lifespans))){
  
f1<-big_data$ref_lifespans
f<-unfactor(f1[k])
ref_lifespan_single<-as.numeric(unlist(strsplit(f, ",")))

avg.ref.ls<-round(mean(c(ref_lifespan_single)))
x<-big_data$id
ref_lifespan_mean<-round(big_data$ref_lifespan_mean[k])
if (avg.ref.ls==ref_lifespan_mean){
  message("mean is correct at id ",x[k])
} else {
  message("mean is wrong at id ",x[k])
}

}


```

```{r,warning=FALSE}

fit_names = c( 'genotype','media','mat','sd.ls','medianLS','Delta_LL','AvgLS','gompLogLik','gompRate','gompShape','weibLogLik','weibScale','weibShape')
fit = data.frame(matrix(, nrow=length(fit_names), ncol=length(fit_names))) #set up a skeleton table
names(fit) = c( "genotype","media","mat","sd.ls","medianLS","Delta_LL","AvgLS","gompLoglik","gompRate","gompShape","weibLogLik","weibScale","weibShape")



for (genotype_in in c(1:length(big_data$ref_name))){
  
  #genotype=117
  
  lifespansChar_set<-big_data$set_lifespans
  lifespansChar_set1<-unfactor(lifespansChar_set[genotype_in])
  lifespansTemp_set =as.numeric(unlist(strsplit(lifespansChar_set1, ",")))
  
  
  
  lifespansChar_ref<-big_data$ref_lifespans
  lifespansChar_ref1<-unfactor(lifespansChar_ref[genotype_in])
  lifespansTemp_ref =as.numeric(unlist(strsplit(lifespansChar_ref1, ",")))
  
  lifespansTemp<-c(lifespansTemp_set,lifespansTemp_ref)             
                       
  
  lifespansTemp[lifespansTemp < 0] <- 0
  lifespansTemp <-floor(lifespansTemp+0.5)
  lifespansTemp <- lifespansTemp[ lifespansTemp != 0 ]
  
  lifespanGomp = flexsurvreg(formula = Surv(lifespansTemp) ~ 1, dist = 'gompertz') ### Use the flexsurvreg package to fit lifespan data to gompertz or weibull distribution
  lifespanWeib = flexsurvreg(formula = Surv(lifespansTemp) ~ 1, dist = 'weibull')  
  
  ### Fill in added columns in the controlConditions table with data from gompertz and weibull fitting. Columns are named according to respective variables
  media<-big_data$ref_media
  media=unfactor(media[genotype_in])
  mat<-big_data$ref_mating_type
  mat=unfactor(mat[genotype_in])
  avgLS = mean(lifespansTemp)
  StddevLS = sd(lifespansTemp)
  medianLS = median(lifespansTemp)
  gompShape = lifespanGomp$res[1,1]
  gompRate = lifespanGomp$res[2,1]
  gompLogLik = lifespanGomp$loglik
  gompAIC = lifespanGomp$AIC
  
  weibShape = lifespanWeib$res[1,1]
  weibScale = lifespanWeib$res[2,1]
  weibLogLik = lifespanWeib$loglik
  weibAIC = lifespanWeib$AIC   
  
  delta_LL = lifespanWeib$loglik- lifespanGomp$loglik
  
  genotype<-big_data$ref_name
  
  genotype=unfactor(genotype[genotype_in])
  
  fit = rbind(fit,c(genotype,media,mat,StddevLS,medianLS,delta_LL,avgLS,gompLogLik,gompRate,gompShape,weibLogLik,weibScale,weibShape))
  
}

new_fit<-fit[length(fit_names)+1:length(fit),]

#hist(new_fit$avgLS)

```



